version: "3.9"

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Rahul@123"
    ports:
      - "1500:1433"
    volumes:
      - type: 'bind'
        target: '/var/opt/mssql/data'
        source: './docker/sqldata/data'

# volumes:
#   sqldata: